name: Test server endpoints

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Test server app
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test server endpoints
        uses: ./
