on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Test app
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Containerized tests
        uses: ./
